org: francoatmega
app: database-trigger
service: aws-node-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:PutItem
        - dynamodb:ListStreams
        - dynamodb:DescribeStreams
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/users"

resources: 
  Resources: 
    UserTable: 
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: "users"
        AttributeDefinitions: 
          - 
            AttributeName: "id"
            AttributeType: "S"
          -
            AttributeName: "name" 
            AttributeType: "S"
          -
            AttributeName: "age"
            AttributeType: "S"
        KeySchema: 
          - 
            AttributeName: "id"
            KeyType: "HASH"
          -
            AttributeName: "name"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
functions:
  user-insert:
    handler: handler.userInsert
    events:
      - http: 
          path: /users
          method: post
          cors: true

  user-trigger:
    handler: handler.userInsertTrigger
    events:
      - stream: 
          type: dynamodb
          arn: 
            Fn::GetAtt:
              - UserTable
              - StreamArn