org: francoatmega
app: s3-and-sqs
service: tooling

frameworkVersion: '3'

plugins:
  - serverless-localstack
  - serverless-mocha-plugin
  - serverless-offline

custom:
  serverless-offline: 
    useChildProcesses: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello