org: francoatmega
app: cron-schedule
service: layers

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

layers:
  moment:
    path: layer
    compatibleRuntimes:
      - nodejs12.x
    allowedAccounts:
      - '*'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: 'hello'
          method: 'get'
    layers:
      - !Ref MomentLambdaLayer
